@echo off
echo islem baslatiliyor...
timeout /t 1 >nul
echo Pip guncelleniyor...
python.exe -m pip install --upgrade pip
timeout /t 1 >nul
echo MSS yukleniyor...
pip install mss
timeout /t 1 >nul
echo Numpy yukleniyor...
pip install numpy
timeout /t 1 >nul
echo Keyboard yukleniyor...
pip install keyboard
timeout /t 1 >nul
echo Mouse yukleniyor...
pip install mouse
timeout /t 1 >nul
echo Pyserial yukleniyor...
pip install pyserial
timeout /t 1 >nul
echo Pywin32 yukleniyor...
pip install pywin32
timeout /t 1 >nul
echo OpenCV-Python-Headless yukleniyor...
pip install opencv-python-headless
timeout /t 1 >nul
echo OpenCV-Python yukleniyor...
pip install opencv-python
timeout /t 1 >nul
echo Pillow yukleniyor...
pip install pillow
timeout /t 1 >nul
echo Requests yukleniyor...
pip install requests
timeout /t 1 >nul
echo Tkinter yukleniyor...
pip install tk
timeout /t 1 >nul
echo Python Imagesearch yukleniyor...
pip install python-imagesearch
timeout /t 1 >nul
echo Python MySQL yukleniyor...
pip install mysql-connector-python
timeout /t 1 >nul
echo Python Requests yukleniyor...
pip install requests
timeout /t 1 >nul
echo Python PIL yukleniyor...
pip install Pillow
timeout /t 1 >nul
echo Python Image Search yukleniyor...
pip install python-imagesearch
timeout /t 1 >nul
echo Python Arduino yukleniyor...
pip install pyfirmata
timeout /t 1 >nul
echo Python Soap yukleniyor...
pip install beautifulsoup4
timeout /t 1 >nul
echo Python Soap xml yukleniyor...
pip install lxml
timeout /t 1 >nul
echo MSS yukleniyor...
pip install mss
timeout /t 1 >nul
echo Numpy yukleniyor...
pip install numpy
timeout /t 1 >nul
echo MSS tekrar yukleniyor...
pip install mss
timeout /t 1 >nul
echo Keyboard yukleniyor...
pip install keyboard
timeout /t 1 >nul
echo Mouse yukleniyor...
pip install mouse
timeout /t 1 >nul
echo Pyserial yukleniyor...
pip install pyserial
timeout /t 1 >nul
echo Pywin32 yukleniyor...
pip install pywin32
timeout /t 1 >nul
echo OpenCV-Python-Headless yukleniyor...
pip install opencv-python-headless
timeout /t 1 >nul
echo Pip guncelleniyor...
pip install --upgrade pip
timeout /t 1 >nul
echo pyautogui guncelleniyor...
pip install pyautogui
timeout /t 1 >nul
echo OpenCV-Python yukleniyor...
pip install opencv-python
timeout /t 1 >nul
echo schedule yukleniyor...
pip install schedule
timeout /t 1 >nul
echo screeninfo yukleniyor...
pip install screeninfo
timeout /t 1 >nul
echo pyarmor yukleniyor...
pip install pyarmor
timeout /t 1 >nul
echo islem tamamlandi.
pause